"""System Design Interview Simulator - Common Schemas and DTOs.

Provides generic API envelopes, pagination metadata, RFC-7807 problem details,
and foundational response structures used across all service endpoints.
"""

from datetime import datetime, timezone
from typing import Generic, TypeVar
from pydantic import Field

from app.schemas import BaseSchema

T = TypeVar("T")


class PaginationParams(BaseSchema):
    """Query parameters for paginated list endpoints."""

    page: int = Field(
        default=1,
        ge=1,
        description="Current page number (1-indexed).",
    )
    page_size: int = Field(
        default=20,
        ge=1,
        le=100,
        description="Number of items to return per page (maximum 100).",
    )

    @property
    def offset(self) -> int:
        """Calculate SQL OFFSET value for database query slicing."""
        return (self.page - 1) * self.page_size

    @property
    def limit(self) -> int:
        """SQL LIMIT alias matching page size."""
        return self.page_size


class PaginationMeta(BaseSchema):
    """Metadata describing a paginated collection result set."""

    page: int = Field(description="Current page number.")
    page_size: int = Field(description="Number of items per page.")
    total_items: int = Field(description="Total count of available items matching query.")
    total_pages: int = Field(description="Total number of pages available.")
    has_next: bool = Field(description="True if another page exists after current.")
    has_previous: bool = Field(description="True if a previous page exists.")

    @classmethod
    def create(cls, page: int, page_size: int, total_items: int) -> "PaginationMeta":
        """Factory constructor computing derived pagination boundaries."""
        total_pages = max(1, (total_items + page_size - 1) // page_size) if total_items > 0 else 1
        return cls(
            page=page,
            page_size=page_size,
            total_items=total_items,
            total_pages=total_pages,
            has_next=page < total_pages,
            has_previous=page > 1,
        )


class PaginatedResponse(BaseSchema, Generic[T]):
    """Standard generic wrapper for paginated collections."""

    items: list[T] = Field(description="List of records for the requested page.")
    pagination: PaginationMeta = Field(description="Pagination bounds and navigation metadata.")


class ApiResponse(BaseSchema, Generic[T]):
    """Uniform REST API response envelope wrapping single-resource payloads."""

    success: bool = Field(default=True, description="Indicates whether request succeeded.")
    message: str = Field(default="Operation completed successfully.", description="Human-readable status.")
    data: T | None = Field(default=None, description="Payload data returned by the operation.")
    timestamp: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
        description="UTC timestamp of response generation.",
    )


class ErrorDetail(BaseSchema):
    """Granular field-level validation or domain error item."""

    loc: list[str] = Field(default_factory=list, description="Field path location of error.")
    msg: str = Field(description="Description of specific constraint violation.")
    type: str = Field(default="value_error", description="Error type code.")


class ErrorResponse(BaseSchema):
    """RFC-7807 compliant problem details response envelope."""

    type: str = Field(
        default="about:blank",
        description="URI reference that identifies the problem type.",
    )
    title: str = Field(description="Short, human-readable summary of problem.")
    status: int = Field(description="HTTP status code generated by origin server.")
    detail: str = Field(description="Human-readable explanation specific to this occurrence.")
    instance: str | None = Field(
        default=None,
        description="URI reference identifying the specific occurrence of the problem.",
    )
    code: str = Field(
        default="INTERNAL_ERROR",
        description="Application domain error code for programmatic handling.",
    )
    errors: list[ErrorDetail] = Field(
        default_factory=list,
        description="Detailed list of validation or subordinate errors.",
    )
    correlation_id: str | None = Field(
        default=None,
        description="Request correlation ID for distributed tracing and log correlation.",
    )
    timestamp: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
        description="UTC timestamp when error occurred.",
    )


class HealthResponse(BaseSchema):
    """Service health and readiness probe response schema."""

    status: str = Field(default="healthy", description="Overall service status (healthy, degraded, unhealthy).")
    version: str = Field(description="Application semantic version.")
    environment: str = Field(description="Deployment environment (development, staging, production).")
    database: str = Field(default="connected", description="PostgreSQL connectivity status.")
    timestamp: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
        description="UTC timestamp of probe execution.",
    )
