"""System Design Interview Simulator - WebSocket Event Framing Schemas.

Defines Pydantic schemas for bi-directional WebSocket communication, covering
inbound candidate dialogue, whiteboard synchronizations, hints, ping/pong heartbeats,
and outbound streaming tokens, stage transitions, and evaluation events.
"""

from datetime import datetime, timezone
from typing import Any
import uuid
from pydantic import Field

from app.core.constants import (
    ArtifactType,
    InterviewStage,
    WebSocketInboundEvent,
    WebSocketOutboundEvent,
)
from app.schemas import BaseSchema


# ---------------------------------------------------------------------------
# Inbound Payload Schemas (Candidate -> Server)
# ---------------------------------------------------------------------------


class WSCandidateMessagePayload(BaseSchema):
    """Payload for candidate chat turns submitted via WebSocket."""

    content: str = Field(
        ...,
        min_length=1,
        description="Candidate text message response, explanation, or question.",
        examples=["I propose placing an API Gateway with rate limiting in front of our services."],
    )
    stage: InterviewStage | None = Field(
        default=None,
        description="Active stage claimed by the candidate client (validated by server state machine).",
    )
    metadata: dict[str, Any] = Field(
        default_factory=dict,
        description="Client-side interaction metadata (e.g. client timestamp, client sequence).",
    )


class WSCanvasUpdatePayload(BaseSchema):
    """Payload for architecture canvas / whiteboard updates emitted by the candidate."""

    artifact_type: ArtifactType = Field(
        default=ArtifactType.ARCHITECTURE_DIAGRAM,
        description="Classification of canvas artifact being edited.",
    )
    title: str = Field(
        default="System Architecture Diagram",
        max_length=255,
        description="Title of the architecture diagram or worksheet.",
    )
    content: str = Field(
        ...,
        description="Serialized diagram state, Mermaid syntax, or canvas node coordinates.",
    )
    version: int = Field(
        default=1,
        ge=1,
        description="Client-side canvas revision version.",
    )
    metadata: dict[str, Any] = Field(
        default_factory=dict,
        description="Canvas viewport, bounding box, or layout engine metadata.",
    )


class WSRequestHintPayload(BaseSchema):
    """Payload when a candidate requests an unblocking hint."""

    stage: InterviewStage = Field(
        ...,
        description="Current interview stage where guidance is requested.",
    )
    topic: str | None = Field(
        default=None,
        description="Optional specific sub-topic or component candidate is stuck on.",
        examples=["Database sharding key selection"],
    )
    tier: int = Field(
        default=1,
        ge=1,
        le=3,
        description="Progressive hint tier (1 = subtle nudge, 2 = guiding question, 3 = direct hint).",
        examples=[1],
    )


class WSSubmitStagePayload(BaseSchema):
    """Payload when candidate signals completion of the current interview stage."""

    current_stage: InterviewStage = Field(
        ...,
        description="Stage candidate is requesting to advance from.",
    )
    notes: str | None = Field(
        default=None,
        description="Optional candidate summary notes before advancing.",
    )


class WSPingPayload(BaseSchema):
    """Client keepalive heartbeat payload."""

    client_time: float = Field(
        ...,
        description="Client epoch timestamp for round-trip latency calculation.",
    )


class WSInboundMessage(BaseSchema):
    """Generic envelope wrapper for all inbound WebSocket events."""

    event: WebSocketInboundEvent = Field(
        ...,
        description="Inbound event discriminator.",
        examples=[WebSocketInboundEvent.CANDIDATE_MESSAGE],
    )
    session_id: uuid.UUID | None = Field(
        default=None,
        description="Interview session UUID (optional if bound to WebSocket connection URL).",
    )
    payload: dict[str, Any] = Field(
        ...,
        description="Structured event payload conforming to the specific event schema.",
    )
    timestamp: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
        description="UTC timestamp when the event was dispatched by the client.",
    )


# ---------------------------------------------------------------------------
# Outbound Payload Schemas (Server -> Candidate)
# ---------------------------------------------------------------------------


class WSInterviewerTokenPayload(BaseSchema):
    """Payload for real-time LLM token streaming chunks."""

    token: str = Field(
        ...,
        description="Individual textual token generated by the interviewer agent.",
        examples=["Consider "],
    )
    index: int = Field(
        ...,
        ge=0,
        description="Monotonically increasing token chunk index within the turn.",
    )
    stage: InterviewStage = Field(
        ...,
        description="Interview stage during which token was generated.",
    )
    message_id: uuid.UUID | None = Field(
        default=None,
        description="Message UUID associated with the streaming turn.",
    )


class WSInterviewerMessageEndPayload(BaseSchema):
    """Payload signaling completion of an interviewer speaking turn."""

    message_id: uuid.UUID = Field(
        ...,
        description="UUID of the fully persisted interviewer message.",
    )
    full_content: str = Field(
        ...,
        description="Complete aggregated response text delivered to the candidate.",
    )
    stage: InterviewStage = Field(
        ...,
        description="Interview stage of this completed turn.",
    )
    token_count: int = Field(
        default=0,
        description="Total tokens consumed by the generation.",
    )
    suggested_next_action: str | None = Field(
        default=None,
        description="Optional UI prompt indicating recommended next candidate action.",
    )


class WSStageTransitionPayload(BaseSchema):
    """Payload notifying client of an interview stage change."""

    session_id: uuid.UUID = Field(description="Interview session UUID.")
    previous_stage: InterviewStage = Field(description="Previous active stage.")
    current_stage: InterviewStage = Field(description="New current active stage.")
    stage_title: str = Field(description="Human-readable title of new stage.")
    stage_description: str = Field(description="Guidance and expectations for new stage.")
    transitioned_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
        description="UTC timestamp of the transition.",
    )


class WSEvaluationReadyPayload(BaseSchema):
    """Payload notifying candidate that their interview scorecard is ready."""

    session_id: uuid.UUID = Field(description="Interview session UUID.")
    evaluation_id: uuid.UUID = Field(description="Generated evaluation scorecard UUID.")
    overall_score: float = Field(
        ...,
        ge=1.0,
        le=5.0,
        description="Overall numerical score.",
    )
    hiring_recommendation: str = Field(
        description="Hiring recommendation summary (e.g. hire, strong_hire).",
    )
    summary: str = Field(
        description="Executive summary of the debrief.",
    )


class WSHintDeliveredPayload(BaseSchema):
    """Payload delivering progressive hint to the candidate."""

    stage: InterviewStage = Field(description="Stage hint was requested in.")
    hint_text: str = Field(description="Textual guidance or question provided by the hint agent.")
    tier: int = Field(ge=1, le=3, description="Progressive hint level delivered.")
    hints_remaining: int = Field(
        default=0,
        description="Remaining hints permitted in this stage without score penalty.",
    )


class WSErrorPayload(BaseSchema):
    """Payload sent when a WebSocket error or validation failure occurs."""

    code: str = Field(
        ...,
        description="Machine-readable error classification code.",
        examples=["INVALID_EVENT", "RATE_LIMIT_EXCEEDED", "SESSION_EXPIRED"],
    )
    message: str = Field(
        ...,
        description="Human-readable explanation of the error.",
    )
    detail: dict[str, Any] | None = Field(
        default=None,
        description="Additional debugging or validation context.",
    )


class WSPongPayload(BaseSchema):
    """Server heartbeat pong response."""

    server_time: float = Field(
        ...,
        description="Server epoch timestamp when pong was returned.",
    )
    client_time: float | None = Field(
        default=None,
        description="Echoed client timestamp for latency calculation.",
    )


class WSOutboundMessage(BaseSchema):
    """Generic envelope wrapper for all outbound server WebSocket events."""

    event: WebSocketOutboundEvent = Field(
        ...,
        description="Outbound event discriminator.",
        examples=[WebSocketOutboundEvent.INTERVIEWER_TOKEN],
    )
    session_id: uuid.UUID = Field(
        ...,
        description="Interview session UUID.",
    )
    payload: dict[str, Any] = Field(
        ...,
        description="Structured event payload conforming to event schema.",
    )
    timestamp: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
        description="UTC timestamp when the event was dispatched by the server.",
    )
